version: "2"
services:
 application:
    image: ${IMAGE_NAME}
    container_name: bank-leads2
    ports:
      - "8080:8080"
    environment:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - MONGO_DB_URL=${MONGO_DB_URL}
        - BUCKET_NAME=${BUCKET_NAME}
        - AWS_ECR_LOGIN_URI=${AWS_ECR_LOGIN_URI}
        - ECR_REPOSITORY_NAME=${ECR_REPOSITORY_NAME}
